export const siteConfig = {
  name: "Helder Burato Berto",
  title: "Helder Burato Berto - Software Engineer",
  description:
    "Experienced Software Engineer with over a decade specializing in React, TypeScript, and modern web development. Sharing expert insights on software architecture, front-end best practices, and engineering leadership to help developers build scalable, high-performance applications.",
  url: "https://helderberto.com",
  ogImage: "/social-cover.png",
  author: {
    name: "Helder Burato Berto",
    email: "helder.burato@gmail.com",
    role: "Senior Software Engineer",
  },
  social: {
    github: "https://github.com/helderberto",
    linkedin: "https://www.linkedin.com/in/helderberto/",
  },
  keywords: [
    "Senior Software Engineer",
    "React Developer",
    "TypeScript Expert",
    "Frontend Architect",
    "Modern Web Development",
    "Technical Leadership",
    "Software Architecture",
    "Engineering Blog",
    "JavaScript Expert",
    "Web Performance Optimization",
    "React Best Practices",
    "Frontend Engineering",
    "Scalable Web Applications",
    "UI/UX Best Practices",
    "Clean Code Principles",
    "Developer Productivity",
    "Engineering Management",
    "Web Application Security",
  ],
  locale: "en_US",
  type: "website",
  themeColor: "#ffffff",
  canonicalUrl: "https://helderberto.com",
  comments: {
    repo: "helderberto/helderberto.com",
    label: "Comment",
  },
} as const;
